=encoding utf8

=for HTML <a href="https://travis-ci.org/zoffixznet/perl6-IRC-Client"><img src="https://travis-ci.org/zoffixznet/perl6-IRC-Client.svg?branch=master"></a>

=head1 NAME

IRC::Client - Extendable Internet Relay Chat client

=head1 SYNOPSIS

    # None yet

=head1 DESCRIPTION

None yet

=head1 REPOSITORY

Fork this module on GitHub:
L<https://github.com/zoffixznet/perl6-IRC-Client>

=head1 BUGS

To report bugs or request features, please use
L<https://github.com/zoffixznet/perl6-IRC-Client/issues>

=head1 AUTHOR

Zoffix Znet L<http://zoffix.com/>

=head1 LICENSE

You can use and distribute this module under the same terms as Perl 6
itself. See the C<LICENSE> file included in this distribution for complete
details.

=cut
